### ISSUE TITLE
make eip authorship depend on ENS

### ISSUE THREAD

**Issue by TimDaub** [ethcatherders/EIPIP#169]
- now that GH and others deleted all of tornado cash dev's accounts I find it unsettling that the EIP process connects the authorization of editing to a GH username
- I don't wanna put more work on you, but wouldn't it be great if EIP authorship was connected to an ENS name and that the author has to sign the commit for it to be merged or smth like that.
- thoughts?

**Comment by poojaranjan** [comment]
Added to agenda #168

**Comment by Pandapip1** [comment]
> now that GH and others deleted all of tornado cash dev's accounts I find it unsettling that the EIP process connects the authorization of editing to a GH username

I have to agree with you here. I wish there was something better than https://radicle.network/ or https://www.valist.io/ for this problem.

**Comment by SamWilsn** [comment]
How would you feel about allowing an Ethereum address as a third option (alongside email and GitHub username) as an option for authenticating authors? I believe you can use secp256k1 private keys for GPG signing.

**Comment by xinbenlv** [comment]
> How would you feel about allowing an Ethereum address as a third option (alongside email and GitHub username) as an option for authenticating authors? I believe you can use secp256k1 private keys for GPG signing.

 @SamWilsn that's great. I will be in favor of this proposal for supporting Ethereum msg signing or ENS as a third option. So long as at least for now people can *also* still use their email and github to authenticate if they choose so.

**Comment by xinbenlv** [comment]
@TimDaub suggest changing the subject to 
<s>make</s>*Allow* eip authorship depend on ENS

**Comment by 5660-eth** [comment]
In fact, I'm using ens as the author name

**Comment by Pandapip1** [comment]
I support allowing ENS **OR** an Ethereum mainnet address. I would not support it if it was *only* ENS.

**Comment by 5660-eth** [comment]
ETH mainnet address is fine.It's just that the ETH  mainnet address may be a bit long.
If using [chat.blockscan](https://chat.blockscan.com/index) or other decentralized chat tools, the author can also be contacted by ETH address or ENS.In addition, the author can also build his own decentralized website with the help of ENS and IPFS.

**Comment by Pandapip1** [comment]
[shameless promotion of my own EIP] With the help of EIP-5219, this can be done with any smart contract.

**Comment by SamWilsn** [comment]
I guess we need to ask ourselves why we have authors and their GitHub or e-mail address. Author names are there for attribution, and we require a GitHub username for automated authentication. While we can perform manual authentication using e-mail, it really isn't a common practice (nor is it something I'd like to encourage.) You could argue that email addresses are there in case we need to contact an author, but generally speaking the `discussions-to` thread is better for that anyway. So we have communication and authentication.

So what benefits does adding an ENS name or Ethereum address bring?

For communication, they're pretty useless. There's no standard way of sending a message to an ENS/address, and while some solutions do exist, I don't think they're widespread enough to use in this process, and again, the `discussion-to` link is probably the best place to have discussions.

We could use an author's ENS/address for automated authentication, but as far as I know, there's no tooling to support signing a commit with an Ethereum private key. There's likely even less tooling to support signing a commit with an ENS name. I'd be much more excited about this ticket if someone could demo a signed commit we could use for authentication.

If we do want to add an authentication method that doesn't depend on GitHub, why not just make a `.pgp` folder, and allow authors of the form `John Doe (6B00E477)` where `6B00E477` is the pgp key id?

**Comment by 5660-eth** [comment]
I think this discussion is based on the following considerations.

> * now that GH and others deleted all of tornado cash dev's accounts I find it unsettling that the EIP process connects the authorization of editing to a GH username

GH is very handy and in most cases it works pretty well. However, it sometimes suffers from censorship-resistant concerns. So the scenario being discussed might be: for some EIP authors, if GH doesn't work well anymore, do we need some fallbacks

**Comment by xinbenlv** [comment]
> I guess we need to ask ourselves why we have authors and their GitHub or e-mail address. Author names are there for attribution, and we require a GitHub username for automated authentication. 

A data point of how EIP author address has been used: I have been using the email addresses on EIP to reach out to authors for questions, suggestions and invitation of peer reviews. 

ENS name or mainnet address helps providing a native way to identify an author.  It also allow us to _depend less_ on Github account systems which is, for now, centralized. For example, author may authenticate and authorize their commit without requiring a github account. Currently it's still unlikely we move away completely from Github soon, but it's a step closer to a better future of EIP.

While it seems slightly premature at this moment to advocate for using ENS to identify authors for now, I think there are benefits when ENS is mature (e.g. when adopted more widely). With the trend of account abtractions, it's possible in the future when everyone uses a smart contract as their wallet and social identity, they might be able to also specify communication channel in their ENS. such as ENS text entries or via something like https://eips.ethereum.org/EIPS/eip-5437

> I support allowing ENS OR an Ethereum mainnet address. I would not support it if it was only ENS.

I support either way or both.

**Comment by g11tech** [comment]
> I support allowing ENS OR an Ethereum mainnet address. I would not support it if it was only ENS.

+1

+1 for pgp key as well

**Comment by poojaranjan** [comment]
Inactive for a year. Please reopen for discussion if you'd like to champion this proposal.
