### ISSUE TITLE
Call for Input: RFC-like back-references?

### ISSUE THREAD

**Issue by bumblefudge** [ethcatherders/EIPIP#306]
## Call for Input

<table>
<tr>
<th>Decision: Should EIPs have backlinks in frontmatter (and display them on the other end when published)?</th>
<td>

Some kind of simple to understand question where affirming/rejecting have clear (non-)actions.

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

@bumblefudge will open a PR on EIP-1 adding `updates` and `replaces` to EIP-1 and the template, including an explanation that any author can use these without approval or consent from authors of updated/replaced EIP.

[I could probably also volunteer to do a MVP of the forward-linking feature on the replaced/updated EIPs if it stays in jekyll but I'm sure others would do it better]
</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

Status quo

</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>February 7, 2024</td>
</tr>
</table>

Sorry I missed today's meeting! At previous meetings, I brought up offhand the analogy to IETF RFCs, which are about as "immutable" as EIPs are once they get finalized, and yet still manage to get updated and/or superceded routinely _without modifying the updated or superceded RFCs_. They achieve this not in the finalized documents themselves (which are, bit-for-bit, immutable in a txt format), but by the rendering of them in the IETF "Datatracker" (the functional equivalent of our EIP static site-generator pipeline, perhaps?).  

## Exhibit A: How IETF RFCs handle this:
This is what it looks like when you search for a superceded and/or updated RFC in datatracker:

![image](https://github.com/ethcatherders/EIPIP/assets/37127325/26f65628-7236-4293-82e2-e55f6b31dbc3)
([Src](https://datatracker.ietf.org/doc/search?name=2223&sort=&rfcs=on&activedrafts=on&by=group&group=))

And this is how it displays at the canonical permalink for a given RFC that has been updated and/or superceded:

![image](https://github.com/ethcatherders/EIPIP/assets/37127325/37e1027b-b3a9-48ad-9007-7e4dc5919635)
([Src](https://datatracker.ietf.org/doc/rfc2223/))

Future RFCs that update or supercede ("obsolete") a finalized one simply mark themselves as such in frontmatter like so:

![image](https://github.com/ethcatherders/EIPIP/assets/37127325/e9d3e89d-cc3b-41d7-a21b-2856871bad85)
([Src](https://raw.githubusercontent.com/ietf-tools/rfcxml-templates-and-schemas/main/draft-rfcxml-general-template-standard-00.xml), linked from [here](https://authors.ietf.org/templates-and-schemas))

These back-references get picked up by the datatracker database and show up whenever the older RFC is displayed by it.

## Exhibit B: How might the EIP process handle "updates" and full-blown supercessions?

I think we could introduce a frontmatter field going forward (before the WG processes diverge too much?) like IETF has for `updates` and/or `obsoletes`/`supercedes`.  Since we are using a static site generator (or perhaps some day soon, various different ones!) to re-render the entire corpus of EIPs each time a PR is merged, this could allow the same functionality, where the HTML page you see when you hit a permanent link could contain "Updated by"/"Superceded by" links the minute an updating or a superceding EIP gets accepted.

Would this help mitigate the various discussions about how to update normative or semi-normative/substantive sections of final EIPs? It feels like the people trying to update final EIPs are quite underwhelmed by the recommended path of "just open a new one" since there's no _forward link_ to these new docs from the old ones...

**Comment by bumblefudge** [comment]
## Caveat implementor

Note that at IETF, there is no "change controller", meaning that anyone can open an RFC that obsoletes a prior one, and it's the responsibility of the WG ratifying that RFC to decide if author Bob is qualified to obsolete the work of author Alice.  This is a non-issue most of the time since RFCs move through WGs that already decided Alice's work was worthy of updating and Bob was qualified to do it when they accepted the draft RFC as a work item... this might be where the analogy breaks down.  

We might want to bikeshed `updates`/`updated-by` and/or `obsoletes`/`supercedes` to be more tentative reflecting the lack of a normative legitimacy to all proposals, like `proposes-update`/`proposed-update` and `proposes-successor`/`proposed-successor` ?  Unless we want to get into complicated gymnastics about making Alice approve Bob's PR 😄

**Comment by SamWilsn** [comment]
@bumblefudge is this a fair distillation of your post down into a few questions?

> Do we want to add an optional field to the preamble (possibly `obsoletes`/`supersedes`/`updates`/etc.) that contains a list of proposals that are replaced by the current proposal? If so, do we want to display a notice on those listed proposals that they've been replaced?

---

Assuming my rewording maintains the spirit of your suggestion, I am **in favour** of doing both.

**Comment by bumblefudge** [comment]
Well, I guess my proposal was twofold, and the other half is kinda work i'm trying to trick you into signing up for 😅 
1.) Add backlink frontmatter props to EIP1+template (including change controller constraints and/or caveats)
2.) Add _forwardlinks_ to the backlinked docs in the publication pipeline 🌶️ 🌶️ 🌶️ 

I think this would be flexible enough to allow all kinds of follow-on docs without violating immutability, but I also suspect that without #2 it won't be very satisfying to the people proposing them in the various open PRs right now!

**Comment by SamWilsn** [comment]
Updated my comment!

**Comment by bumblefudge** [comment]
LFG

**Comment by shemnon** [comment]
I find @bumblefudge's caveat concerning, especially because "any author can use these without approval or consent from authors of updated/replaced EIP."  I expect we will see people using it against other EIPs simply because they disagree with the design decisions of other authors.  With the IETF process they at least need to gain the approval of the WG chair to add the change.

Could we add that it then requires consent of the EIP editors or authors of the referenced EIP to add a supercedes/updates tag?

**Comment by abcoathup** [comment]
I'm in favor (but don't have a vote)

**Comment by SamWilsn** [comment]
> Could we add that it then requires consent of the EIP editors or authors of the referenced EIP to add a supercedes/updates tag?

Making this a permissioned field either:
- Puts EIP Editors in the position of having to decide (removing credible neutrality), or
- Gives authors the power to reject a perfectly valid replacement for non-technical reasons (eg. profit, competition, etc.)

I'll only support this field if it's permissionless, and the forward-links are something like:

> Superseded by: 1234, 1235, 5432
>
> Please note that _any_ proposal may _claim_ to supersede this one, and this list is provided for information only. These links may not be endorsed by the authors of this proposal or by the EIP Editors.

**Comment by shemnon** [comment]
I don't support the ability to obsolete an existing  spec in a permissionless fashion.  But I'm not an editor.

**Comment by bumblefudge** [comment]
If this took a "permissionless" form, I think there will still be a de facto distinction made by the EIP audience between "blessed" follow-ons and supercessions (e.g. adding one of the original authors as a co-author before going final) and totally independent or even antagonist ones-- I'm not sure the git process needs to formalize this, tho (it would, if nothing else, make for lots of editor headaches to be in the loop and having to act differently depending on whether a target-author has signed off "officially"  or not).

Would it help to bikeshop the semantics?  Maybe copy-pasting the IETF terms without bringing along the WG governance confuses the nature of the thing, and a more permissionless process would be implied by different terms?

|original|alternative1|alternative2|help me out here guys|
|---|---|---|---|
|replaces|forks|challenges|???|
|replaced by|forked as|challenged by|???|
|updates|extends|depends on|???|
|updated by|extended-by|downstream|???|

**Comment by bumblefudge** [comment]
> I don't support the ability to obsolete an existing spec in a permissionless fashion. Even with the caveat it's a claim. But I'm not an editor.

Well, technically, we already have this, and people propose upgrades or replacements for existing mechanisms all the time-- we we just don't have a mechanism for pointing to all proposed obsoleting EIPs from a given EIP!  Which is why i'm so fixated on the exact mechanism by which backlinks get expressed as forwardlinks

**Comment by SamWilsn** [comment]
> adding one of the original authors as a co-author before going final

With today's tooling, you do not need to consent to be added an an author.

**Comment by bumblefudge** [comment]
[backstory/rabbitholes here](https://github.com/ethereum/EIPs/issues/5265)

**Comment by g11tech** [comment]
after thinking about this issue: i am opposed because if this is permissionless (and permissioned doesn't make sense as mentioned by @SamWilsn ) its a spam vector for people to suggest "updates" on popular EIPS

**Comment by SamWilsn** [comment]
@g11tech are you worried about completely useless proposals cluttering up popular ones, or legitimate-but-unlikely-to-be-adopted proposals doing it?

**Comment by g11tech** [comment]
> @g11tech are you worried about completely useless proposals cluttering up popular ones, or legitimate-but-unlikely-to-be-adopted proposals doing it?

Completely useless can we weeded out, it's the second category but we only activate the forward link when the proposal is adopted (for EIP driven by ACD it might make sense, for ERCs and RIPs where it might now)

**Comment by SamWilsn** [comment]
How would you feel about giving it a try for some fixed period (say a year) and see how much crap accumulates?

**Comment by bumblefudge** [comment]
I would actually argue that "unlikely-to-be-adopted" (at the SC/Wallet layer where there is never a binary adoption decision like the ACD upgrade schedule) is a bigger problem which is orthogonal to this mechanism-- whether such EIPs are linked to from the older EIP they extend or require has no influence on how many never-adopted ERCs this process allows, or the incentives for writing them.

I say we adopt this ASAP for the benefit of giving a clear recommendation to people doing BCP and security addenda, and then turn our attention to the relationship between documents and adoption at the SC/Wallet layer, which is a bigger problem and unlikely to be solved by any tweaks (or lack thereof) to the document process or its publication tooling.

**Comment by bumblefudge** [comment]
(Spoiler alert: I think Solidity Summit and Wallet Working Group could maybe be directing traffic and discouraging "frivolous" ERC proposals to create something like an ACD equivalent at higher levels of the stack. But that's off-topic here, I would argue?)

**Comment by bumblefudge** [comment]
after discussing on EIPIP today, I feel more strongly than ever that some form of "replacement"/mutually-incompatible-version semantic is worth keeping.  "fork" seems to encompass both the ACD categories (mapped to specific hard forks) and the ERC category (at the app level, replacements are forks, whether "friendly" or not)...

**Comment by SamWilsn** [comment]
@g11tech:

> As long as the clutter can be managed, I am fine with it.

@gcolvin:

> For mainnet, it just happens automatically. The main purpose of having superseded would be to stop implementers from implementing an out-of-date proposal. I can see a need for it, but I'm not quite sure whether we want to do it this way.

**Comment by SamWilsn** [comment]
I don't feel like there is a consensus to move forward (I'm the only one strongly in favour) with this as proposed, but I also don't feel like there's opposition to the fundamental idea&mdash;just concerns about permissionless spam.

_If_ we go ahead with Working Groups, I think that kind of structure may be more friendly to `supersedes`. For now, however, I think we should close this and not make any changes.

**Comment by gcolvin** [comment]
As happens too often I notice the closing of an issue too late, but I agree with the outcome.

If even some parts of an EOF go in there will be code that used to be OK to put onchain which no longer passes validation, at which point an EIP might in some sense be superseded or obsolete -- we can cross that bridge when we come to it.  But any EIP that went onchain can never be totally obsolete, as it specifies behavior that has to keep on working for old contracts and for code dynamically generated by old contracts..

When a WG has taken responsibility for an ERC then an earlier ERC can be superseded in the sense that it is no longer, in their judgement, best practice.  And for things like RIPs, where I understand the main purpose is assuring interoperability, then it definitely makes sense to indicate whether new RIPS are compatible with old ones.  Again, we can cross that bridge when we come to it.

In all cases the WGs themselves will need to be part of the consensus.
