### ISSUE TITLE
Call for Input: Adding Additional Author to ERC-5169

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#308]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/184 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

@charlesfus is added as an author to [ERC-5169](https://eips.ethereum.org/EIPS/eip-5169) (Final.)

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No new author is added.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>February 8th, 2024</td>
</tr>
</table>

# Background

@JamesSmartCell (an original author of [ERC-5169](https://eips.ethereum.org/EIPS/eip-5169)) would like to add @charlesfus as an author. ERC-5169 is final.

**Comment by g11tech** [comment]
but why? again authors is not the credit list and we shouldnt treat it like that. so unless it needs maintenance which it does not I vote NO

**Comment by abcoathup** [comment]
Final is final, I vote no (but don't have a vote).  There shouldn't be changes after an ERC is final, it is too late to add an author.  They can do credits elsewhere e.g. on a website for the ERC.

**Comment by xinbenlv** [comment]
@JamesSmartCell, could you state your justification here? We haven't had precedents for adding an author, nor do we have precedents for rejecting a request to add an author; hence, I think it's worthy of a discussion. Also, can you join the EIPIP meeting next Wednesday? That would be a good venue to make your case before the editors.

**Comment by lightclient** [comment]
I vote no

**Comment by bumblefudge** [comment]
i'd rather PR EIP-1 to make the semantic of `authorship` strictly change-control, not credit or endorsement.

**Comment by SamWilsn** [comment]
@gcolvin feels pretty strongly that `authors` should represent people who make meaningful contributions to the document, even if it means changing it after Final.

**Comment by SamWilsn** [comment]
For my part, @g11tech convinced me with this argument, roughly quoted:

> EIPs aren't here to pump people's resumes. I can imagine someone bribing authors of a popular EIP to get authorship credit, and we don't want to be in the business of dealing with that.

---

I am **against** adding a new author.

**Comment by SamWilsn** [comment]
The prevailing opinion is to not modify a final EIP.

**Comment by gcolvin** [comment]
> authors is not the credit list and we shouldnt treat it like that

I disagree.  I suggest you ask the Duck or the Google about "authorship credit."  

This is an Errata.  I've added the need for an Errata section to the next meeting agenda.

**Comment by SamWilsn** [comment]
Hopefully I correctly noted your objection correctly in https://github.com/ethcatherders/EIPIP/issues/308#issuecomment-1919705435.

**Comment by gcolvin** [comment]
Yes, you have.  And I'm pointing out that it's not just my own opinion.  We can discuss it on the Agenda issue.  https://github.com/ethcatherders/EIPIP/issues/312
