### ISSUE TITLE
Call For Input: rename `author(s)` to `maintainer(s)` or `proposer(s)`

### ISSUE THREAD

**Issue by g11tech** [ethcatherders/EIPIP#317]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we rename `author(s)` to `maintainer(s)` or `proposer(s)` in the EIP/ERC/RIP headers and webfronts

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

The EIP header and renderings will be renamed from `author(s)` to `maintainer(s)` or `proposer(s)`, and the process documents be updated to signal the new semantics of the field.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>March 20th, 2024</td>
</tr>
</table>

# Background

Refer to the discussions on 
- https://github.com/ethcatherders/EIPIP/issues/308

Where it was discussed allowing an author to be added to a final EIP. A consensus for doing the same couldn't be reached for the same for reasons enumerated in the issue.

In light of the fact that its not feasible to `credit` every one involved unless rigorous references are mentioned and checked against (and also necessitating the need to evaluate `authorship` claims), it is suggested via this "Call for Input" to change the semantics of `author` to `maintainer` and hence reflect the same. 

Once the EIP/ERC/RIP is submitted, the IP and copyright is waived off and hence belongs to the community, and the only relevance of the current `author(s)` field is permissions for them to update it till it is adopted by the community. 

This can also resolve issues, where the current author of a `stagnent` EIP no longer supports it and EIP editors can take executive decision add someone else who is more motivated (can happen again via Call For input, but its an orthogonal issue but nevertheless the semantics change allows us to do this if the current author for e.g. is not cooperative for their `stagnent` EIP)

**Comment by SamWilsn** [comment]
So "author" is definitely the more recognized term in publishing, but I do agree that it doesn't transfer well here. For one, being an author implies that you agree to release your content under CC0, but you do not need to consent to being added as an author, so a misbehaving author could add, say, Brian Armstrong (CEO of Coinbase) to an EIP to give the impression that Coinbase releases the work to the public domain, when in fact they do not.

On the other hand, there is a significant amount of work in renaming the field. The renderer would need to be updated along with `eipw`, not to mention third-party integrations like airdrops.

---

For the above reasons, I am choosing to **abstain** for the time being.

**Comment by lightclient** [comment]
I vote no here, I don't think there is a problem to solve here.

**Comment by g11tech** [comment]
> Rather than renaming, why not add an explicit definition to EIP-1 of what an author is and isn't.

may be this is the minimum we can do

**Comment by SamWilsn** [comment]
I don't really see a clear consensus. @g11tech is likely in favour since he made this proposal, and @lightclient has clearly expressed his opposition. I'm going to close this as rejected, but am fine with re-opening if there's more discussion to be had.
