### ISSUE TITLE
Call for Input: Allow links to PQClean

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#318]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8245 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

Links to [PQClean](https://github.com/PQClean/PQClean/) are allowed.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>March 20th, 2024</td>
</tr>
</table>

# Background

See https://github.com/ethereum/EIPs/pull/8190

**Comment by abcoathup** [comment]
No: (I don't have a vote)
We already have nine types of linking to external resources.  My preference is not to keep adding to this.
https://eips.ethereum.org/EIPS/eip-1#linking-to-external-resources

**Comment by SamWilsn** [comment]
I am also **opposed** to adding an exception for this specific project.

**Comment by SamWilsn** [comment]
This is past the deadline, and the general consensus appears to be to not merge this PR.
