### ISSUE TITLE
Call for Input: Update ERC-6492 (Final) Reference Implementation

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#321]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/267 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

[ERC-6492](https://eips.ethereum.org/EIPS/eip-6492)'s reference implementation is updated.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>March 22th, 2024</td>
</tr>
</table>

**Comment by g11tech** [comment]
reference implementation change and notices (security considerations for e.g. in 291) we should be able to update, will keep EIPs fresh but we need a good process to verify such a change

**Comment by SamWilsn** [comment]
So is your opinion here, @g11tech, that we should or should not merge this PR?

**Comment by SamWilsn** [comment]
Thanks for clarifying. Closing this one since the only responses are opposed, but I am open to discuss a more comprehensive policy.

**Comment by Ivshti** [comment]
@g11tech @SamWilsn what do you guys think about re-doing the PR in the following way:

- no changes to the original text
- new section under "security considerations" called "Audit report"
- "Audit report" section contains a *link* to the PDF and an updated `.sol` file post-audit, perhaps to a diff between the included reference implementation and the new one
- @SamWilsn's comment regarding license is resolved

**Comment by SamWilsn** [comment]
See https://github.com/ethcatherders/EIPIP/issues/291#issuecomment-1789265565 for a bit more detail on my reasoning, but the short form is Final means Final, and we only allow updates to correct errors in the specification.
