### ISSUE TITLE
Call for Input: Update Author's Username in EIP-1193

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#325]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8290/files ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

[EIP-1193](https://eips.ethereum.org/EIPS/eip-1193)'s author list is updated.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>April 7th, 2024</td>
</tr>
</table>

## Background

@lightclient has verified the identity of the author. The old username has been re-registered by a different person.

**Comment by SamWilsn** [comment]
I am **in favour** of merging as long as the identity of the author is well verified.

**Comment by lightclient** [comment]
I am also in favor and have identified the individual.

**Comment by xinbenlv** [comment]
While I personally agree and want the individual to have the right to update their username despite EIP being final. Wearing a EIP editor hat, it seems according to https://github.com/ethcatherders/EIPIP/issues/308 this case shall be rejected, which I personally disagree but it was a case we made as a group so we shall follow the same rationale.

I ask my fellow EIP editors who vote in favor to provide a rationale of how this is different from https://github.com/ethcatherders/EIPIP/issues/308 or we shall update our policy

**Comment by lightclient** [comment]
@xinbenlv this is different than #308 imo because we're changing the username of a listed author to be correct with their current username, rather than modifying the actual list of people.

**Comment by xinbenlv** [comment]
Thank you @lightclient for answering. I have no objection if our lines is drawn at "updating username for EIP is ok even when it's a final EIP".

Here is a similar case: someone sent me an email claiming to be ERC-5855 co-author and ask to update the user name

<img width="466" alt="image" src="https://github.com/ethcatherders/EIPIP/assets/640325/b25bf2b6-3251-495b-bdeb-691c86561621">


I've replied and ask them to present their case here too for us to consider the rule

**Comment by xinbenlv** [comment]
Propose to repurpose this Call for Input as "Policy involving updating author's username in EIP/ERCs" considered the 3 cases

1. For any authors filed a PR to change their username in EIP/ERCs of final or any status allowing edit: if lead author individually or a number of greater than half of the remaining authors other than requesting author attested the new username is the intended co-author by leaving comment in the PR, the update to username shall be considered legit.
2. Given sufficient attestants, Any single EIP editor shall be able to approve the merge the PR.
3. Special case: if there is only one listed author, any EIP Editor could vouch for their identity, another EIP Editor can merge the PR to update the username.

**Comment by bumblefudge** [comment]
s/legit/sufficiently authorized/*

**Comment by apan826** [comment]
I completely agree with the proposal raised by @xinbenlv. For a simple reason, we cannot accept that the name of a reward to me is not me. I think we need to have a way to update it. Thanks!

**Comment by lightclient** [comment]
I don't think we need more policies. There is enough work to do, we don't need arbitrary procedures for hypothetical issues holding us back.

**Comment by apan826** [comment]
I just think we need to have a way to update the wrong author name.

**Comment by apan826** [comment]
O really? Is there a guide for it? Thanks!

lightclient ***@***.***> 于2024年3月15日周五 20:15写道：

**Comment by apan826** [comment]
> We do, it's up to editor discretion.

Hi, @lightclient Can you let me know what does "editor discretion" mean? I really want to update the author name of my EIP... thanks!

**Comment by wolovim** [comment]
data point possibly worth highlighting: as it stands, whoever is the current owner of `marcgarreau` has the potential to abuse this amendment approval ability. in practice, i'd have faith in the remaining EIP authors and editors to police it.

<img width="929" alt="Screenshot 2024-03-20 at 11 04 09 AM" src="https://github.com/ethcatherders/EIPIP/assets/3621728/afc88954-2cd1-4c7a-a239-8dced6fe3992">

thats all from me though. thanks to you who've put brain power into it. 🫡

**Comment by xinbenlv** [comment]
I support authors to have a way to update their Github handle or contact information. @apan826 do you have a PR?

**Comment by xinbenlv** [comment]
> I strongly oppose any process which isn't repeatable by any author. Knowing an EIP editor shouldn't get you different/special treatment, than if you were a complete random. EIP editors shouldn't pick winners.

I share @abcoathup 's view. 

I created a Call for Input: https://github.com/ethcatherders/EIPIP/issues/329

**Comment by apan826** [comment]
> I support authors to have a way to update their Github handle or contact information. @apan826 do you have a PR?

Hi, @xinbenlv You mean the PR for updating my username in the author list of EIP5585? If yes, I did not create a PR yet, do I need to create one? Thanks.

**Comment by xinbenlv** [comment]
Yes, please, and also have either your lead author approving it, or more than half of your other co-authors approve that PR as a way to validate the request, then I will go on to get it merged

**Comment by apan826** [comment]
Hi, @xinbenlv  this is the PR created by our major author, thanks!
https://github.com/ethereum/ERCs/pull/367

**Comment by g11tech** [comment]
its a terrible thing that other username has been registered by a different person, i am ok updating this but this is sort of a hassle we should avoid with some auto renaming or having a crypto identity (onchain or otherwise)

**Comment by SamWilsn** [comment]
General consensus is to affirm.

**Comment by apan826** [comment]
> its a terrible thing that other username has been registered by a different person, i am ok updating this but this is sort of a hassle we should avoid with some auto renaming or having a crypto identity (onchain or otherwise)

Hi, @g11tech, it is a good point, I agree.

**Comment by apan826** [comment]
Hi, @xinbenlv @lightclient @SamWilsn @g11tech can we move to the link please and help to approve, https://github.com/ethereum/ERCs/pull/405 , exactly the same thing,  sorry and many thanks.
