### ISSUE TITLE
Call for Input: Change Solidity in Final ERC-7201

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#327]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/201 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

[ERC-7201](https://eips.ethereum.org/EIPS/eip-7201)'s specification section is modified.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>April 12th, 2024</td>
</tr>
</table>

## Background

Changing:

```patch
- keccak256(abi.encode(uint256(keccak256(id)) - 1)) & ~bytes32(uint256(0xff))
+ keccak256(abi.encode(uint256(keccak256(bytes(id))) - 1)) & ~bytes32(uint256(0xff))
```

**Comment by SamWilsn** [comment]
I am **in favour** of merging this pull request. It seems to correct an error in the original document without changing its meaning.

**Comment by abcoathup** [comment]
I support merging (I don't have a vote).
Whilst I am generally against modifying final EIPs, this is a correction that is approved by one of the authors.  Though we need a standard process for agreeing corrections.

**Comment by g11tech** [comment]
in favor of fixing typos

**Comment by SamWilsn** [comment]
The consensus on this issue seems to be merging, so merge I shall!
