### ISSUE TITLE
Call for Input: how should we decide whether a PR updating author list of a Final EIP/ERC/RIP be merged or rejected?

### ISSUE THREAD

**Issue by xinbenlv** [ethcatherders/EIPIP#329]
## Call for Input

Decision: How should we decide whether a PR  updating author list of a Final EIP/ERC/RIP be merged or rejected?
- Option 1: approve at editor discretion
- Option 2: approve at editor consensus
- Option 3: approve by lead author or author consensus
- Option 4: other, please suggest

Method: Rough Consensus
Deadline: April 29th, 2024

## Background
https://github.com/ethcatherders/EIPIP/issues/325#issuecomment-1995174481

**Comment by xinbenlv** [comment]
> Call for Input

**Comment by SamWilsn** [comment]
I don't think modifying a final proposal should be any different than any other potentially contentious decision: open a rough consensus call for input.

**Comment by g11tech** [comment]
simple reject

**Comment by SamWilsn** [comment]
@xinbenlv's preferred option is 3 I think?
