### ISSUE TITLE
Call for Input: Change Author Username in ERC-6672

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#331]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/285/files ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

[ERC-6672](https://eips.ethereum.org/EIPS/eip-6672)'s author list is updated.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>May 2nd, 2024</td>
</tr>
</table>

## Background

@SamWilsn has verified the identity of the author by email.

**Comment by SamWilsn** [comment]
I am **in favour** of merging this pull request.

**Comment by SamWilsn** [comment]
@xinbenlv has also expressed support on the pull request.

**Comment by g11tech** [comment]
i guess we would want to reflect the new names but as @abcoathup mentions, its better done by some repeatable process

**Comment by SamWilsn** [comment]
Is "open a Call for Input" an insufficiently repeatable process?

**Comment by xinbenlv** [comment]
my stance:
- Authors holds the power to update name or contact, not editors. Editors merely facilitate authors to update it when tooling hasnt support author do it on their own
- What is considered a prerequisite to update username shall be consistent and transparent

If that needs to be in errata instead of the preemble its fine to me. I am fine either way.

**Comment by lightclient** [comment]
I approve

**Comment by abcoathup** [comment]
@SamWilsn 
> Is "open a Call for Input" an insufficiently repeatable process?

Call for input is too slow, takes up too much governance resources and should be for exceptions.  
If the agreement is that username changes will be allowed under certain conditions (which appears to be the consensus) then any editor can merge when the conditions are met.  e.g. >50% of authors approve

**Comment by SamWilsn** [comment]
> Call for input is too slow

If editors responded more quickly/reliably, this wouldn't be an issue. The deadline is only there to keep things moving when some editors don't participate.

Is changing usernames on a final proposal a time sensitive issue?

> If the agreement is that username changes will be allowed under certain conditions (which appears to be the consensus) then any editor can merge when the conditions are met. e.g. >50% of authors approve

This comes up rarely enough that I don't think we need a formal process. We're like... six people. Just ask one of us to make the change, and we can sort it out.

**Comment by xinbenlv** [comment]
> Call for input every time seems to be too slow and requires unnecessary consensus of editors which is scarce resource, but I am ok if everyone wants to do call for input.

For the context of this issue, I am in favor while with a different reason

**Comment by SamWilsn** [comment]
The general consensus seems to be to merge this pull request.
