### ISSUE TITLE
Call For Input: Should we entertain the typo correction PRs

### ISSUE THREAD

**Issue by g11tech** [ethcatherders/EIPIP#332]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Should we merge the typo correction PRs which might just be people farming via contributions

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

we merge such PRs

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>such PRs will be closed</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>May 8 2024</td>
</tr>
</table>

## Context

Such kind of PRs https://github.com/ethereum/EIPs/pull/8254 

may be we should add a spell checker in the first place?

**Comment by g11tech** [comment]
I am against entertaining such PRs and closing them off

**Comment by SamWilsn** [comment]
I am **in favour** of merging pull requests fixing typos.

---

> may be we should add a spell checker in the first place?

Theoretically [we have one](https://github.com/ethereum/EIPs/blob/ea55bb3f9e64d03737f7ac22b0b855e30af2abfd/.github/workflows/ci.yml#L104-L129). Not sure why it isn't working.

**Comment by SamWilsn** [comment]
Doesn't seem to be a strong consensus either way. I'm going to close this for now, but can reopen if we need to.
