### ISSUE TITLE
Call for Input: Change Author Username in ERC-5585

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#333]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we change the author username @apan to @apan826?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

We merge the pull request https://github.com/ethereum/ERCs/pull/367/.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

We close https://github.com/ethereum/ERCs/pull/367/ without merging.

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

May 10, 2024

</td>
</tr>
</table>

### Background

Note that the creator of the pull request is not an author of the proposal. I **have not** verified the new username.

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
With @fovcao's (original author) approval on https://github.com/ethereum/ERCs/pull/367, I am **in favour** of merging.

**Comment by xinbenlv** [comment]
In favor

**Comment by abcoathup** [comment]
I'm generally against changing final EIPs.  
If this change was to be merged, they should get at least 2, preferably 3 authors to approve.

**Comment by travelnotes** [comment]
I am in favor of the update. It makes sense to only update the author's account but not the content of the EIP.

**Comment by SamWilsn** [comment]
I guess the person making this pull request has withdrawn it. @apan826 @crypto-yus if you're interested in pursuing this, please comment here.

**Comment by SamWilsn** [comment]
I take that back. I guess it's over here now: https://github.com/ethereum/ERCs/pull/405

**Comment by SamWilsn** [comment]
General consensus is to merge.
