### ISSUE TITLE
Call for Input: Fix Comment in ERC-3448

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#343]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/429?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

Comment in reference implementation is changed.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

ERC-3448 is unchanged.

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

July 28, 2024

</td>
</tr>
</table>

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
I'm **in favour** of merging, after a quick bytecode scan.

**Comment by abcoathup** [comment]
Given it is correcting a comment, if the ERC author approves then I'm ok with this, even though I am generally against changing final ERCs.  The discussions topic on Eth Magicians should be changed to a wiki post and have a corrections section.

**Comment by g11tech** [comment]
ok with the change

**Comment by lightclient** [comment]
seems okay
