### ISSUE TITLE
Call for Input: Mark 7212 as "Moved"

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#345]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8101 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

EIP-7212 is marked as "Moved", an unusual status.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

Pull request is not merged, and 7212 remains both an EIP and an RIP.

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

August 2, 2024

</td>
</tr>
</table>

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
I am **in favour** of merging this pull request.

**Comment by abcoathup** [comment]
**I would prefer Withdrawn rather than a one off status of Moved.  But am not opposed to merging.** (but don't have a vote) 

Move means copy and delete, so ideally we would delete (completely remove) the EIP but there are already references to it (such as https://eips.ethereum.org/EIPS/eip-7600).

In future, moving an EIP to a RIP, we should issue the RIP a new number and set the EIP to Withdrawn, rather than creating another state to maintain.

**Comment by poojaranjan** [comment]
IMO, EIP-7212 should be treated the same way as ERCs when EIPs GitHub repo was forked. We can use the same process for RIP-7212 because when moved it carried the number which was allocated to an EIP.

**Comment by poojaranjan** [comment]
EIP-7212 was also discussed in the ACDE meeting as it is being considered for the Pectra upgrade. Adding screenshots of suggestions that surfaced.
![Screenshot 2024-07-04 at 10 49 03 AM](https://github.com/ethcatherders/EIPIP/assets/29681685/22174788-5fa0-4031-a876-1f6165e74de2)

**Comment by ulerdogan** [comment]
As the co-author of EIP/RIP-7212, I support merging this PR and bring 'Moved' status for the original EIP. I agree that it's a similar situation with ERCs and this necessity has been mentioned in the first RollCalls. This action will resolve recent confusion around the 7212 proposal and opens the space for L1 to directly implements an RIP or make changes by a new EIP if required.

**Comment by lightclient** [comment]
I think we should delete it

**Comment by g11tech** [comment]
+1 for delete

**Comment by SamWilsn** [comment]
Delete is fine by me.

**Comment by abcoathup** [comment]
@SamWilsn deadline is August 2 (today in Australia).  3 votes for delete.

Would be good to get this resolved (regret not renumbering the RIP).
EIP version of RIP7212 is considered for inclusion in Pectra, was discussed on ACDE 193 (https://ethereum-magicians.org/t/all-core-devs-execution-acde-193-august-1-2024/20648/2) but inclusion will be reviewed in a few months.

**Comment by SamWilsn** [comment]
Consensus is to delete.

**Comment by SamWilsn** [comment]
https://github.com/ethereum/EIPs/pull/8779
