### ISSUE TITLE
Call for Input: Merge Update to EIP-152

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/EIPIP#348]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8390 ?

</td> 
</tr>
<tr>
<th>If Affirmed</th>
<td> Update EIP-152 after 3 Editors approval in absence of author's approval

</td>
</tr>
<tr>
<th>If Rejected</th>
<td> Do not merge the PR until approved by one of the original co-authors.

</td>
</tr>
<tr>
<th>Method</th>
<td> Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td> Aug 17, 2024

</td>
</tr>
</table>

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [ ] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [ ] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
I am **in favour** of merging.

**Comment by abcoathup** [comment]
I am against without at least one author approving.

**Comment by SamWilsn** [comment]
With a shocking voter turnout of one, I've gone ahead and merged https://github.com/ethereum/EIPs/pull/8390

Most editors approved it, so I'm reasonably comfortable with my decision.
