### ISSUE TITLE
Call for Input: Update Final ERC-7540

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#364]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/ERCs/pull/670 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

https://github.com/ethereum/ERCs/pull/670 is merged

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

No change

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

November 15, 2024

</td>
</tr>
</table>

### Background

Changing some event names in the text to match the YAML description.

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
**In Favour**

**Comment by abcoathup** [comment]
I'm against unless a majority of authors approve the change.  

EIP editors shouldn't be choosing here.  UPDATE: A majority of authors have approved ~It should be the majority of authors, so far it is 2 out of 6, they need two more to approve.~

**Comment by SamWilsn** [comment]
Before a proposal is final, we only require a single author's approval for changes. I don't see why we need to make it a majority after. The process for changing a final proposal could be:

1. Is this clearly a mistake?
2. Does the proposed change fix the mistake?
3. Is the proposed change the smallest correction possible?

Author approval helps with (1) and (2) but I don't even think it's strictly required (though I'm a lot more comfortable with it than without.)

**Comment by abcoathup** [comment]
> Before a proposal is final, we only require a single author's approval for changes. I don't see why we need to make it a majority after.

A non-final standard is expected to have some changes, though ideally these are smaller as it gets closer to final.

A final standard isn't expected to have any changes.  Users should be able to build/implement using the standard safely without the concern that it will change underneath them.  We don't have version numbers, so any non-trivial change should really be a new EIP/RIP/ERC.

If changes to final standards are allowed (and I am generally against this), the bar to make a change should be really high.  
The responsibility shouldn't be on editors to decide if a change is correct.  This should be on the authors.  Hence we should require a majority of authors to approve any change to a standard.

1 & 2 should be the decisions of the majority of authors.  Editors shouldn't have this responsibility.
3 is where editors can help guide, but ultimately it is on the authors.

In this specific case two events have been renamed and a parameter added to a method.  This is something that authors should approve/not approve.

**Comment by hieronx** [comment]
@SamWilsn @abcoathup the PR has now been approved by 4/6 authors: https://github.com/ethereum/ERCs/pull/670 Working on reaching out to the other two as well but hopefully this suffices already!

**Comment by abcoathup** [comment]
@hieronx glad you now have a majority of authors approving with 4/6.  I am against any changes to final ERCs but wouldn't oppose one which is approved by the majority of authors.

If the change is allowed by editors I recommend adding an Update Log to the Eth Magicians discussions topic.  (See: https://ethereum-magicians.org/t/template-for-discussion-to-threads/20347)  So that you can clearly communicate with ERC users when/why this change was made.

**Comment by hieronx** [comment]
We are at 5/6 approvals now.

> If the change is allowed by editors I recommend adding an Update Log to the Eth Magicians discussions topic. (See: https://ethereum-magicians.org/t/template-for-discussion-to-threads/20347) So that you can clearly communicate with ERC users when/why this change was made.

Good idea, we'll do that!

**Comment by hieronx** [comment]
@SamWilsn @abcoathup am I correct in assuming this is now approved and the PR can be merged?

**Comment by abcoathup** [comment]
> am I correct in assuming this is now approved and the PR can be merged?

@SamWilsn was the only editor who voted and the deadline has passed, but need to wait for Sam to decide.

**Comment by poojaranjan** [comment]
We should simplify the process and not add rules unless necessary. 
- Approving changes to a `Final` proposal is totally up to the editors to approve. 
- Before and after moving to `Final` status, only one author approval suffice in case changes proposed are by a non-author.
- After the Call for Input deadline is passed, it is up to the 'Keeper' to determine if a rough consensus has been reached. Every EIP Editor is entitled to have their opinion heard and understood before the Keeper makes that determination.

**Comment by hieronx** [comment]
@SamWilsn would you be able to comment on this and help move this forward? Thanks!

**Comment by SamWilsn** [comment]
I'm generally not comfortable closing a CFI without more editor input, but my colleagues seem  to be pretty silent on this one... I've approved the PR.
