### ISSUE TITLE
Call for Input: Allow links to ISO 4217's currency list

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#367]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we allow links to ISO 4217's list of currencies?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

EIP-1 is updated, and https://github.com/ethereum/ERCs/pull/688 is merged.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

No changes.

</td>
</tr>
<tr>
<th>Method</th>
<td>

Rough Consensus

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

December 4, 2024

</td>
</tr>
</table>

### Background

Generally we don't allow links to ISO standards because they are behind a paywall. ISO 4217 is no exception, but its list of currencies _is_ available free of charge: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
**opposed**

---

This goes against the spirit of EIP-5757. You can't even read the standard that this list is a part of without paying a fee.

**Comment by abcoathup** [comment]
**Opposed**

EIP5757 says no links to paywalls, if you can't read the standard then it is a hard no.

**Comment by SamWilsn** [comment]
To be clear, the currency list itself is available for free, but the standard is not. I think the list technically meets 5757's requirements.

**Comment by g11tech** [comment]
yea opposed since its not free standard

**Comment by bumblefudge** [comment]
all my homeys hate closed standards processes

**Comment by SamWilsn** [comment]
Closing as rejected.
