### ISSUE TITLE
Call for Input: Editor Removal (@gcolvin)

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#368]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we remove @gcolvin as an Editor?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

@gcolvin is moved to emeritus and removed from the yaml files.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>

No change

</td>
</tr>
<tr>
<th>Method</th>
<td>

Unanimous (minus the Editor being removed)

</td>
</tr>
<tr>
<th>Deadline</th>
<td>

December 4, 2024

</td>
</tr>
</table>

### Background

[EIPs reviewed in the past year: 2](https://github.com/ethereum/EIPs/pulls?q=is%3Apr+reviewed-by%3Agcolvin+created%3A%3E2023-10-01+)
[ERCs reviewed in the past year: 0](https://github.com/ethereum/ERCs/pulls?q=is%3Apr+reviewed-by%3Agcolvin+created%3A%3E2023-10-01+)

### Checklist

I, the opener of this Call for Input, have completed the following:

- [x] Filled in a descriptive title.
- [x] Filled in the "Decision" field.
- [x] Filled in the "If Affirmed" field.
- [x] Filled in the "If Rejected" field.
- [x] Filled in the "Method" field.
- [x] Filled in the "Deadline" field to be thirty days from creation.
- [x] Added any relevant background information (or removed the section.)
- [x] Published a notice in writing to the usual channels frequented by EIP Editors (likely Discord.)
- [x] Commented on this Call for Input, clearly stating my opinion (or abstention.)

**Comment by SamWilsn** [comment]
**in favour**

---

Greg has not been active over the past year, so I believe he should be removed from active editor status. That said, I'd support his return in the future.

**Comment by abcoathup** [comment]
**In favor**

------
If you aren't an active editor (for whatever reason) it is best to step down.  My preference is that editors step down themselves.

EIP-1 Emeritus EIP editors is to acknowledge the amazing contribution of past editors.

Plus you can return as an editor.

**Comment by lightclient** [comment]
In favor. Hopefully they are interested in contributing again in the future!

**Comment by SamWilsn** [comment]
Closing as affirmed.
